---
- name: Change file content
  ignore_errors: true
  hosts: localhost
  tasks:
    - name: Change /tmp/file
      lineinfile:
        path: /tmp/file
        regexp: '^Hello World'
        insertbefore: '^line2'
        line: 'This is test'
        create: yes
